In [1]:
import pandas as pd
import numpy as np

In [4]:
# Name of the CSV file
file = 'citibike-nov22.csv'
# The correct encoding must be used to read the CSV in pandas
nov_df = pd.read_csv(file, encoding="ISO-8859-1")
nov_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7B06EEA21608591A,classic_bike,2022-11-12 14:47:21,2022-11-12 14:58:55,Newport PATH,JC066,7 St & Monroe St,HB304,40.727146,-74.033620,40.746413,-74.037977,casual
1,B22A3E8765F1E165,classic_bike,2022-11-30 08:29:53,2022-11-30 08:45:56,Newport PATH,JC066,7 St & Monroe St,HB304,40.727216,-74.033609,40.746413,-74.037977,member
2,CFB2EB1663C02BB6,electric_bike,2022-11-09 08:28:30,2022-11-09 08:44:50,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member
3,85700816DAAE1C36,electric_bike,2022-11-30 14:48:11,2022-11-30 14:58:10,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member
4,009EBB1F54C5947E,electric_bike,2022-11-10 18:14:33,2022-11-10 18:23:08,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member

In [5]:
# Name of the CSV file
file2 = 'citibike-dec22.csv'
# The correct encoding must be used to read the CSV in pandas
dec_df = pd.read_csv(file2, encoding="ISO-8859-1")
dec_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,099D81CA71EBADAB,classic_bike,2022-12-23 16:02:26,2022-12-23 16:09:40,Mama Johnson Field - 4 St & Jackson St,HB404,Adams St & 11 St,HB507,40.743140,-74.040041,40.750916,-74.033541,member
1,D979F3B79FC30F1F,electric_bike,2022-12-27 10:54:29,2022-12-27 10:59:23,Jersey & 3rd,JC074,Marin Light Rail,JC013,40.723332,-74.045953,40.714584,-74.042817,member
2,3950909BC3B42E43,classic_bike,2022-12-31 10:39:39,2022-12-31 11:00:52,Morris Canal,JC072,LaGuardia Pl & W 3 St,5721.14,40.712252,-74.038188,40.729170,-73.998102,member
3,372E50F5FB4FD434,classic_bike,2022-12-05 08:16:10,2022-12-05 08:20:09,Morris Canal,JC072,Columbus Drive,JC014,40.712419,-74.038526,40.718355,-74.038914,member
4,AB701FB8091C7431,classic_bike,2022-12-02 13:40:36,2022-12-02 13:46:11,Harborside,JC104,Grove St PATH,JC005,40.719252,-74.034234,40.719586,-74.043117,member

In [6]:
nov_df.count()

ride_id               72709
rideable_type         72709
started_at            72709
ended_at              72709
start_station_name    72699
start_station_id      72699
end_station_name      72430
end_station_id        72430
start_lat             72709
start_lng             72709
end_lat               72609
end_lng               72609
member_casual         72709
dtype: int64

In [7]:
dec_df.count()

ride_id               48585
rideable_type         48585
started_at            48585
ended_at              48585
start_station_name    48585
start_station_id      48585
end_station_name      48377
end_station_id        48377
start_lat             48585
start_lng             48585
end_lat               48502
end_lng               48502
member_casual         48585
dtype: int64

In [8]:
# Concatenate all dataframes into one
combined_df = pd.concat([nov_df, dec_df], axis=0)
combined_df

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,7B06EEA21608591A,classic_bike,2022-11-12 14:47:21,2022-11-12 14:58:55,Newport PATH,JC066,7 St & Monroe St,HB304,40.727146,-74.033620,40.746413,-74.037977,casual
1,B22A3E8765F1E165,classic_bike,2022-11-30 08:29:53,2022-11-30 08:45:56,Newport PATH,JC066,7 St & Monroe St,HB304,40.727216,-74.033609,40.746413,-74.037977,member
2,CFB2EB1663C02BB6,electric_bike,2022-11-09 08:28:30,2022-11-09 08:44:50,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member
3,85700816DAAE1C36,electric_bike,2022-11-30 14:48:11,2022-11-30 14:58:10,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member
4,009EBB1F54C5947E,electric_bike,2022-11-10 18:14:33,2022-11-10 18:23:08,Newport PATH,JC066,7 St & Monroe St,HB304,40.727224,-74.033759,40.746413,-74.037977,member
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48580,D438F1622839AC50,classic_bike,2022-12-06 15:43:38,2022-12-06 15:53:57,Dey St,JC065,Riverview Park,JC057,40.737828,-74.067083,40.744319,-74.043991,member
48581,747A63A8E782D171,electric_bike,2022-12-08 08:17:51,2022-12-08 08:23:33,9 St HBLR - Jackson St & 8 St,HB305,City Hall - Washington St & 1 St,HB105,40.747907,-74.038412,40.737360,-74.030970,casual
48582,AE090858CFDE6E82,electric_bike,2022-12-23 14:10:07,2022-12-23 14:14:18,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743140,-74.040041,40.737360,-74.030970,member
48583,B3CC8E70AF4E259C,classic_bike,2022-12-02 04:43:25,2022-12-02 04:46:55,Mama Johnson Field - 4 St & Jackson St,HB404,City Hall - Washington St & 1 St,HB105,40.743135,-74.040080,40.737360,-74.030970,member
48584,176B601F21327350,classic_bike,2022-12-30 14:50:17,2022-12-30 14:55:37,14 St Ferry - 14 St & Shipyard Ln,HB202,City Hall - Washington St & 1 St,HB105,40.752747,-74.024035,40.737360,-74.030970,member

In [10]:
# Save the dataframe to a CSV file
combined_df.to_csv('citibike.csv', index=False)